### ISSUE TITLE
Lineages not accepted

### ISSUE THREAD

**Issue by afedynak** [Ellmen/alcov#27]
Hello,

I am having an issue where lineages added to the lineages.txt file are not accepted by alcov, for example XBB.1.22 I get the following error:

File "/usr/local/lib/python3.8/dist-packages/alcov/lineages.py", line 375, in <listcomp>

    lin_mut_profiles = [[round(mut_lins[mut][lin]) for mut in covered_muts] for lin in lineages]

KeyError: 'Omicron (XBB.1.22-like)'

Thank you.

**Comment by JennKnapp** [comment]
This is because there is no constellation in the updated alcov for XBB.1.22 (there is one for XBB.1.22.1 however). With the recent changes to how constellations are made, only lineages with more than 100 sequences on cov-spectrum are included in alcov. You can find all the constellation files in "alcov/alcov/data/constellations/" and any of these lineage names can be added to a 'lineages.txt' file to restrict the lineages alcov uses for predictions (to use all lineages for prediction there is no need for a 'lineages.txt' file).
